name: CI/CD React Deployment

on:
  push:
    branches:
      - master #The workflow runs only when you push to the master branch.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #The job runs on a fresh Ubuntu virtual machine provided by GitHub.

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 #pulls your code from GitHub so the workflow can access it.

      - name: Setup Node
        uses: actions/setup-node@v3 #installs Node.js (latest LTS version) so the React app can build.
        with:
          node-version: 'lts/*'

      - name: Install deps
        run: npm ci #Installs dependencies exactly from package-lock.json

      - name: Build project
        run: npm run build

      # ðŸ‘‰ Upload build folder to EC2
      - name: Upload build folder
        uses: appleboy/scp-action@v0.1.7 #This step uses SCP (secure copy) to upload your build files to your EC2 server.
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'build/*'
          target: '/var/www/my-profile/'
          strip_components: 1 #removes the parent build folder so the contents go directly into /var/www/my-profile/

      # ðŸ‘‰ Restart nginx
      - name: SSH reload nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo nginx -t
            sudo systemctl reload nginx
